Sub ProcessHybridWebsitesFromTextFile()

    Dim utilWb As Workbook
    Dim websiteList As Variant, websitePair As Variant, website1 As Variant, website2 As Variant
    Dim saveFileName As String
    Dim filterRange As Range
    Dim ws As Worksheet
    Dim filePath As String, fileContent As String, fileNum As Integer
    Dim newWb As Workbook, combinedSheet As Worksheet 'Added combinedSheet
    Dim lastRow As Long
    Dim i As Long
    Dim missingDataWebsites As String
    Dim outputFilePath As String, outputFileNum As Integer
    Dim projectCode As String
    Dim subfolderPath As String
    Dim nativeWs As Worksheet, nextGenWs As Worksheet
    Dim nativeLastRow As Long, nextGenLastRow As Long
    Dim nativeFilterRange As Range, nextGenFilterRange As Range
    Dim rowsFoundNative As Boolean, rowsFoundNextGen As Boolean
    Dim j As Long 'Generic counter
    Dim logString As String  'String to build the log messages

    ' ** HOW TO VIEW THE CONSOLE LOGS: **
    ' 1.  Press ALT + F11 to open the VBA editor.
    ' 2.  Press CTRL + G to open the Immediate Window. This is your "console".
    ' 3.  As the code runs, the log messages generated by `Debug.Print` will appear here.
    '     You can clear the Immediate Window by clicking inside it and pressing CTRL+A then DEL.

    ' Tell Excel not to Update the screen
    Application.ScreenUpdating = False

    Set utilWb = ThisWorkbook
    Set nativeWs = utilWb.Sheets("AllData-Data Transfer")
    Set nextGenWs = utilWb.Sheets("AllData-Data Transfer NG")

    missingDataWebsites = "" ' Initialize empty string

    ' ** 1. Get the file path using Application.GetOpenFilename
    filePath = Application.GetOpenFilename(FileFilter:="Text Files (*.txt), *.txt", Title:="Select Text File with Hybrid Website List")

    ' Check if the user cancelled
    If filePath = "False" Then ' User pressed Cancel
        Debug.Print "User cancelled file selection."
        MsgBox "File selection cancelled.", vbInformation
        Exit Sub
    End If

    Debug.Print "Selected file path: " & filePath

    ' ** 2. Read the file content
    fileNum = FreeFile ' Get the next available file number
    Open filePath For Input As #fileNum
    fileContent = Input(LOF(fileNum), fileNum) ' Read entire file into fileContent
    Close #fileNum

    Debug.Print "File content read successfully."

    ' ** 3. Split the file content into a website list
    websiteList = Split(fileContent, ",")

    Debug.Print "Website list created. Number of websites: " & UBound(websiteList) - LBound(websiteList) + 1

    ' ** 4. Process each website and save it to file
    subfolderPath = ThisWorkbook.Path & "\OutputFiles" ' Name of the subfolder

    ' Check if the subfolder exists. If not, create it.
    If Dir(subfolderPath, vbDirectory) = "" Then
        MkDir subfolderPath ' Creates the subfolder
        Debug.Print "Output folder created at: " & subfolderPath
    Else
        Debug.Print "Output folder already exists at: " & subfolderPath
    End If

    ' Loop through all the specified websites
    For Each websitePair In websiteList
        websitePair = Trim(websitePair)

        If websitePair <> "" Then
            Debug.Print "Processing website pair: " & websitePair

            ' Split the website pair into individual websites
            Dim websites() As String
            websites = Split(websitePair, "/")
            Dim numWebsites As Long
            numWebsites = UBound(websites) - LBound(websites) + 1

            Debug.Print "Number of websites in pair: " & numWebsites

            ' Initialize the flag for missing data check
            Dim missingDataFound As Boolean
            missingDataFound = False

            'Clear filters at the beginning of each website processing
            On Error Resume Next
            nativeWs.AutoFilterMode = False
            nextGenWs.AutoFilterMode = False
            On Error GoTo 0

            Debug.Print "Cleared any existing filters on Native and NextGen sheets."

            ' ** Check number of Websites **
            If numWebsites = 2 Then
                website1 = Trim(websites(0))
                website2 = Trim(websites(1))
                Debug.Print "Websites in pair: website1 = " & website1 & ", website2 = " & website2

                ' ** SEARCH NATIVE **
                rowsFoundNative = False
                nativeLastRow = nativeWs.Cells(Rows.Count, "A").End(xlUp).Row
                Set nativeFilterRange = nativeWs.Range("A1:Z" & nativeLastRow)
                Debug.Print "Native - Last Row: " & nativeLastRow

                If Not nativeFilterRange Is Nothing Then
                    nativeFilterRange.AutoFilter Field:=3, Criteria1:=website1
                    If nativeWs.Range("A1:A" & nativeLastRow).SpecialCells(xlCellTypeVisible).Count > 1 Then
                        rowsFoundNative = True
                    Else
                        rowsFoundNative = False
                    End If
                End If

                Debug.Print "Native - Rows found for website1 (" & website1 & "): " & rowsFoundNative

                ' ** SEARCH NEXTGEN **
                rowsFoundNextGen = False
                nextGenLastRow = nextGenWs.Cells(Rows.Count, "A").End(xlUp).Row
                Set nextGenFilterRange = nextGenWs.Range("A1:Z" & nextGenLastRow)
                Debug.Print "NextGen - Last Row: " & nextGenLastRow

                If Not nextGenFilterRange Is Nothing Then
                    nextGenFilterRange.AutoFilter Field:=4, Criteria1:=website2
                    If nextGenWs.Range("A1:A" & nextGenLastRow).SpecialCells(xlCellTypeVisible).Count > 1 Then
                        rowsFoundNextGen = True
                    Else
                        rowsFoundNextGen = False
                    End If
                End If

                Debug.Print "NextGen - Rows found for website2 (" & website2 & "): " & rowsFoundNextGen

            ElseIf numWebsites = 1 Then
                website1 = Trim(websites(0))
                website2 = website1
                Debug.Print "Single website: website1 = website2 = " & website1

                ' ** SEARCH NATIVE **
                rowsFoundNative = False
                nativeLastRow = nativeWs.Cells(Rows.Count, "A").End(xlUp).Row
                Set nativeFilterRange = nativeWs.Range("A1:Z" & nativeLastRow)
                Debug.Print "Native - Last Row: " & nativeLastRow

                If Not nativeFilterRange Is Nothing Then
                    nativeFilterRange.AutoFilter Field:=3, Criteria1:=website1

                    If nativeWs.Range("A1:A" & nativeLastRow).SpecialCells(xlCellTypeVisible).Count > 1 Then
                        rowsFoundNative = True
                    Else
                        rowsFoundNative = False
                    End If
                End If

                Debug.Print "Native - Rows found for website1 (" & website1 & "): " & rowsFoundNative

                ' ** SEARCH NEXTGEN **
                rowsFoundNextGen = False
                nextGenLastRow = nextGenWs.Cells(Rows.Count, "A").End(xlUp).Row
                Set nextGenFilterRange = nextGenWs.Range("A1:Z" & nextGenLastRow)
                Debug.Print "NextGen - Last Row: " & nextGenLastRow

                If Not nextGenFilterRange Is Nothing Then
                    nextGenFilterRange.AutoFilter Field:=4, Criteria1:=website2
                    If nextGenWs.Range("A1:A" & nextGenLastRow).SpecialCells(xlCellTypeVisible).Count > 1 Then
                        rowsFoundNextGen = True
                    Else
                        rowsFoundNextGen = False
                    End If
                End If

                Debug.Print "NextGen - Rows found for website2 (" & website2 & "): " & rowsFoundNextGen

            Else
                Debug.Print "Invalid website format in the file: " & websitePair
                MsgBox "Invalid website format in the file: " & websitePair, vbCritical
                GoTo NextWebsite
            End If

            ' ** Process Data if ANY rows were found in EITHER native or Nextgen **
            If rowsFoundNative Or rowsFoundNextGen Then
                Debug.Print "Rows found in either Native or NextGen.  Creating new workbook."

                ' ** Create a new workbook and combined sheet **
                Set newWb = Workbooks.Add
                Set combinedSheet = newWb.Sheets(1)

                ' ** Copy the Headers **
                If rowsFoundNative Then
                    nativeFilterRange.Rows(1).Copy combinedSheet.Range("A1")
                    Debug.Print "Copied Native headers."
                ElseIf rowsFoundNextGen Then
                    nextGenFilterRange.Rows(1).Copy combinedSheet.Range("A1")
                    Debug.Print "Copied NextGen headers."
                End If


                Dim nextRow As Long
                nextRow = 2  'Start at row 2 to skip headers in new sheet

                ' ** Copy Native Data **
                If rowsFoundNative Then
                    nativeFilterRange.SpecialCells(xlCellTypeVisible).Offset(1, 0).Copy combinedSheet.Cells(nextRow, "A") 'Offset(1,0) to skip headers
                    Debug.Print "Copied Native data to combined sheet. Starting row: " & nextRow

                    'update the nextRow variable for the NEXT dataset
                    nextRow = combinedSheet.Cells(Rows.Count, "A").End(xlUp).Row + 1
                    Debug.Print "Next row after Native data: " & nextRow
                End If


                ' ** Copy NextGen Data **
                If rowsFoundNextGen Then
                    nextGenFilterRange.SpecialCells(xlCellTypeVisible).Offset(1, 0).Copy combinedSheet.Cells(nextRow, "A")  'Offset(1,0) to skip headers
                    Debug.Print "Copied NextGen data to combined sheet.  Starting row: " & nextRow

                    'update the nextRow variable for the NEXT dataset
                    nextRow = combinedSheet.Cells(Rows.Count, "A").End(xlUp).Row + 1
                    Debug.Print "Next row after NextGen data: " & nextRow
                End If


                ' ** Data Validation Loop **
                Dim sourceLastRow As Long
                sourceLastRow = combinedSheet.Cells(Rows.Count, "A").End(xlUp).Row
                Debug.Print "Data Validation Loop - Source Last Row: " & sourceLastRow

                For i = 2 To sourceLastRow 'Start at row 2 to skip headers
                    Dim missingColumns As String ' Buffer to store the missing column names

                    missingColumns = "" ' Initialize the buffer

                    ' Check if Project Code value is available
                    If IsEmpty(combinedSheet.Cells(i, "C").Value) Then
                        missingColumns = missingColumns & "Project Code, "
                        Debug.Print "Data Validation Loop - Missing data in row " & i & " - Project Code"
                    End If

                    ' Tier Checking (Assuming NextGen rules apply to combined data for simplicity)
                    Dim tierValue As String
                    Dim tierCheck As Boolean ' Flag to determine if the tier condition is met

                    tierValue = combinedSheet.Cells(i, "E").Value ' Tier column for nextgen
                    tierCheck = (tierValue = "Large") ' Parenthesis used to create readability


                    ' Check if the tier condition is met AND if K, L, or M are empty
                    If tierCheck Then
                        ' Check if CDN Cache value is available
                        If IsEmpty(combinedSheet.Cells(i, "K").Value) Then
                            missingColumns = missingColumns & "K, "
                            Debug.Print "Data Validation Loop - Missing data in row " & i & " - K"
                        End If

                        ' Check if HA value is there
                        If IsEmpty(combinedSheet.Cells(i, "L").Value) Then
                            missingColumns = missingColumns & "L, "
                            Debug.Print "Data Validation Loop - Missing data in row " & i & " - L"
                        End If

                        ' Check if Eligible for Discount value is there
                        If IsEmpty(combinedSheet.Cells(i, "M").Value) Then
                            missingColumns = missingColumns & "M, "
                            Debug.Print "Data Validation Loop - Missing data in row " & i & " - M"
                        End If
                    End If

                    ' Check if any columns were missing
                    If missingColumns <> "" Then
                        ' Remove the trailing comma and space
                        missingColumns = Left(missingColumns, Len(missingColumns) - 2)

                        missingDataWebsites = missingDataWebsites & websitePair & " (Missing data: " & missingColumns & ")" & Chr(13) & Chr(10) ' Add website and missing columns to the list
                        missingDataFound = True
                        Debug.Print "Data Validation Loop - Missing data found for website pair: " & websitePair & " - Missing columns: " & missingColumns
                        Exit For ' Break early if we find one row with missing data
                    End If
                Next i


                ' ** Clean up **
                ' ** Jira Ticket Link Update **
                Dim jiraLastRow As Long
                jiraLastRow = combinedSheet.Cells(Rows.Count, "A").End(xlUp).Row
                Debug.Print "Jira Ticket Link Update - Jira Last Row: " & jiraLastRow

                For j = 2 To jiraLastRow
                    Dim jiraLink As String, extractedValue As String

                    ' ** Remove Hyperlinks from Column Q **
                    If combinedSheet.Cells(j, "Q").Hyperlinks.Count > 0 Then
                        combinedSheet.Cells(j, "Q").Hyperlinks.Delete
                    End If

                    jiraLink = combinedSheet.Cells(j, "Q").Value ' Get value from column Q

                    If Not IsEmpty(jiraLink) And InStr(1, jiraLink, "https://jira.cwp2.cloudvanti.com/browse/") > 0 Then
                        extractedValue = Mid(jiraLink, InStrRev(jiraLink, "/") + 1)
                        combinedSheet.Cells(j, "Q").Value = "https://jira.cwp2.cloudvanti.com/servicedesk/customer/portal/1/" & extractedValue
                        Debug.Print "Jira Ticket Link Update - Row " & j & " - Updated link to: " & combinedSheet.Cells(j, "Q").Value
                    End If
                Next j

                ' ** Delete Columns **
                ' A is the recording date
                ' N is either Has Subsite or Action
                ' O is Total Base with Subsite
                ' P is Remark
                With combinedSheet
                    .Columns("P").Delete
                    .Columns("O").Delete
                    .Columns("N").Delete
                    .Columns("A").Delete
                End With
                Debug.Print "Deleted Columns A, N, O, and P from combined sheet."

                ' ** FORMATTING **
                With combinedSheet.Range("A1:M" & combinedSheet.UsedRange.Rows.Count)
                    .Cells.Interior.Color = RGB(255, 255, 255) ' White
                    .Cells.Font.Color = RGB(0, 0, 0) ' Black
                    .Cells.Font.Name = "Calibri"
                    .Cells.Font.Size = 12
                    .VerticalAlignment = xlCenter
                    .HorizontalAlignment = xlCenter
                    .Borders.LineStyle = xlContinuous
                    .Borders.Weight = xlThin
                End With
                Debug.Print "Applied general formatting to combined sheet."

                ' ** Header Row Formatting **
                With combinedSheet.Range("A1:M1")
                    .Interior.Color = RGB(0, 148, 200)
                    .Font.Color = RGB(255, 255, 255)
                End With
                Debug.Print "Applied header formatting to combined sheet."

                'Autofit columns and rows
                With combinedSheet
                    .Columns.AutoFit
                    .Rows.AutoFit
                End With
                Debug.Print "AutoFit columns and rows of combined sheet."

                ' ** SAVE FILE NAME **
                ' Get project code from the NEXTGEN sheet if available
                If rowsFoundNextGen Then
                    On Error Resume Next
                    projectCode = nextGenWs.Range("C2:C" & nextGenLastRow).SpecialCells(xlCellTypeVisible)(1, 1).Value
                    On Error GoTo 0
                    Debug.Print "Project Code extracted from NextGen: " & projectCode
                Else
                    projectCode = "N/A" ' Or some default value if NextGen data is missing
                    Debug.Print "Project Code not found in NextGen.  Using default value: N/A"
                End If

                saveFileName = subfolderPath & "\Native and NextGen - Additional Data Transfer - " & Replace(websitePair, "/", " - ") & " - " & projectCode & ".xlsx"

                On Error Resume Next
                Application.DisplayAlerts = False
                newWb.SaveAs Filename:=saveFileName, FileFormat:=xlOpenXMLWorkbook
                Application.DisplayAlerts = True
                newWb.Close SaveChanges:=False
                If Err.Number <> 0 Then
                    Debug.Print "Error saving file (" & saveFileName & "): " & Err.Description
                    MsgBox "Error saving file (" & saveFileName & "): " & Err.Description, vbCritical
                End If
                On Error GoTo 0

                Debug.Print "Saved and closed the new workbook: " & saveFileName

            End If 'End if any rows were found

            nativeWs.AutoFilterMode = False
            nextGenWs.AutoFilterMode = False
            Debug.Print "Cleared filters from Native and NextGen sheets."

        End If

NextWebsite:
    Next websitePair ' Continue to the next website pair
    Debug.Print "Finished looping through websites."
    ' End For Each website in websiteList
    ' ** Create output text file **
    outputFilePath = ThisWorkbook.Path & "\missing-data-report-Hybrid.txt"

    If missingDataWebsites <> "" Then
        Debug.Print "Missing data found. Creating report file: " & outputFilePath

        outputFileNum = FreeFile
        Open outputFilePath For Output As #outputFileNum
        Print #outputFileNum, "Websites with missing data:" & Chr(13) & Chr(10)
        Print #outputFileNum, missingDataWebsites
        Close #outputFileNum

        Debug.Print "Report file created successfully."
        MsgBox "Done processing the websites.  A report has been generated at " & outputFilePath, vbInformation
    Else
        Debug.Print "No missing data found."
        MsgBox "Done processing the websites. No missing data found.", vbInformation
    End If


    ' Tell Excel to continue updating the screen to show the user the result
    Application.ScreenUpdating = True
    Debug.Print "Macro finished."

End Sub
